"""initial schema

Revision ID: 4224110d1703
Revises: 
Create Date: 2026-03-03 12:15:50.838861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4224110d1703'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('winning_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_type', 'draw_date', name='uq_game_draw')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_combinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('combination', sa.String(length=30), nullable=False),
    sa.Column('is_system_expanded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('combination_id', sa.UUID(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('prize_tier', sa.String(length=50), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['combination_id'], ['ticket_combinations.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_results')
    op.drop_table('ticket_combinations')
    op.drop_table('tickets')
    op.drop_table('draw_results')
    # ### end Alembic commands ###
